set MONITORING_DATA_DIRECTORY=D:\GenevaAgent\Data

set MONITORING_TENANT=%USERNAME%

set MONITORING_ROLE=twswarmGenevaProd

set MONITORING_ROLE_INSTANCE=%COMPUTERNAME%

set MONITORING_GCS_ENVIRONMENT=DiagnosticsPROD

set MONITORING_GCS_ACCOUNT=twswarmGenevaProd

set MONITORING_GCS_NAMESPACE=twswarmGenevaProd

set MONITORING_GCS_REGION=westus2

set MONITORING_GCS_THUMBPRINT=e7b0dc8d7b9731badc3bf4f13f1a5a9b68d209f2

set MONITORING_GCS_CERTSTORE=LOCAL_MACHINE\MY

set MONITORING_CONFIG_VERSION=1.1

set MDM_MONITORING_ACCOUNT=twshotGenevaProd

MonAgentLauncher.exe -useenv
